services:
  # Legacy with apt disabled
  ubuntu.18.04:
    deploy:
      replicas: 0
    privileged: true
    environment:
      - GOCOVERDIR=/app/coverage/int/ubuntu/18.04
    build:
      context: .
      target: bionic
      dockerfile: .docker/Ubuntu.dockerfile
    volumes:
      - "./coverage/int/ubuntu/18.04:/app/coverage/int/ubuntu/18.04"
  ubuntu.22.04:
    deploy:
      replicas: 0
    privileged: true
    environment:
      - GOCOVERDIR=/app/coverage/int/ubuntu/22.04
    build:
      context: .
      target: jammy
      dockerfile: .docker/Ubuntu.dockerfile
    volumes:
      - "./coverage/int/ubuntu/22.04:/app/coverage/int/ubuntu/22.04"
  ubuntu.24.04:
    privileged: true
    environment:
      - GOCOVERDIR=/app/coverage/int/ubuntu/24.04
    build:
      context: .
      target: noble
      dockerfile: .docker/Ubuntu.dockerfile
    volumes:
      - "./coverage/int/ubuntu/24.04:/app/coverage/int/ubuntu/24.04"
  fedora.39:
    deploy:
      replicas: 0
    privileged: true
    environment:
      - GOCOVERDIR=/app/coverage/int/fedora/39
    build:
      context: .
      target: legacy
      dockerfile: .docker/Fedora.dockerfile
    volumes:
      - "./coverage/int/fedora/39:/app/coverage/int/fedora/39"
  fedora.40:
    privileged: true
    environment:
      - GOCOVERDIR=/app/coverage/int/fedora/40
    build:
      context: .
      target: previous
      dockerfile: .docker/Fedora.dockerfile
    volumes:
      - "./coverage/int/fedora/40:/app/coverage/int/fedora/40"