// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Status A status response
type Status struct {
	// LastRound Last round the status has knowledge of
	LastRound *float32 `json:"lastRound,omitempty"`

	// NeedsUpdate If the node requires and update
	NeedsUpdate *bool `json:"needsUpdate,omitempty"`

	// Network Network ID
	Network *string `json:"network,omitempty"`

	// State The state of the node
	State *string `json:"state,omitempty"`

	// Version Version reported by the node
	Version *string `json:"version,omitempty"`

	// Voting If the network is voting on an upgrade
	Voting *bool `json:"voting,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve current status
	// (GET /status)
	GetStatus(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStatus(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/status", wrapper.GetStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4xTTW/TQBD9K6OBo4lbkDj4VgmEIiFUpYUL4rDxTuJt7Zlld9woivzf0a4dRyQp4jba",
	"ee/Nx745YC2dFybWiNUBY91QZ3L4oEb7HFmKdXBenTBWeAcxZyBQ9MKRsEAfxFNQRxnfmqgr6dlekr+a",
	"qBBSDrSho1JjIjyz7FqyWwLZYIG694QVct+tKeBQIBPZ+N1bo3Qpu9xkORZLEOh37wJFMGyhHwmz3lqk",
	"JcOjoO4kPF+KfRsTsPx04kUNjreJllq+0sHjNE1qf+7lGv+FQsyUc4UfYwICeQlKFtb7fwuJpujVXUxT",
	"uAgjEoTBMPR+G4y9tpJhfpL1E9WKQ3pyvJFUpBZWU2sK2XQJddduJTW3cIIF9qHFChtVH6uyNKdceWQO",
	"xbmT7pdAbL04VthIgMSykKxkEiQuUpdO22M1C6vPD49wd79MmXmT+GFx+zHJiyc23uWXm8VtMqbRJnuy",
	"jLOdt5SnmMssLVb4hXQyfIFHY2f0+5ub4/jEmWi8b12dqeVTHL9yvJsUvQ20wQrflKfDKqerKqcKea9/",
	"r2KVS1rYOW1ghhUY+64zYZ8RGhy9ENR9CMQ63c4oFimkbWD183D2EZ1xzKTvjHeL+VPqVnpb4lCco5Wi",
	"/j96TWpeRf8a/gQAAP//zqI1+lwEAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
